# Sprint Retro Input - Project Intelligence
name: sprint-retro-input
description: "Generate data-driven observations for retrospectives (Cycle Time, WIP, Blockers)."
author: "PIM"

# Critical variables from bmm config
config_source: "{project-root}/_bmad/bmm/config.yaml"
implementation_artifacts: "{config_source}:implementation_artifacts"

# Workflow components
installed_path: "{project-root}/_bmad/pim/workflows/sprint-retro-input"
instructions: "{installed_path}/instructions.md"

# Inputs
sprint_status_file: "{implementation_artifacts}/sprint-status.yaml"

# Smart input file patterns
input_file_patterns:
  sprint_status:
    description: "Source of truth for sprint items and timestamps"
    whole: "{implementation_artifacts}/sprint-status.yaml"
    load_strategy: "FULL_LOAD"
